from io import BytesIO
from flask import send_file
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
import os
import qrcode
from datetime import datetime
from flask import current_app

def export_to_pdf(title, headers, rows, filename="report.pdf"):
    """Generate and return a styled PDF file."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)

    elements = []

    # Title
    title_style = ParagraphStyle(
        name="TitleStyle",
        fontSize=18,
        alignment=1,  # center
        spaceAfter=20,
        textColor=colors.HexColor("#2C3E50"),
    )
    elements.append(Paragraph(title, title_style))
    elements.append(Spacer(1, 12))

    # Table data
    data = [headers] + rows

    # Table style
    #table = Table(data, repeatRows=1)
    table = Table(data, colWidths=[30, 120, 100, 100, 80, 70])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#34495E")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#ECF0F1")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F9F9")]),
    ]))
    elements.append(table)

    # Footer
    footer_style = ParagraphStyle(
        name="FooterStyle",
        fontSize=10,
        textColor=colors.HexColor("#7F8C8D"),
        alignment=2,
        spaceBefore=20
    )
    elements.append(Paragraph("Generated by Maintenance System", footer_style))

    # Build
    doc.build(elements)
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=filename,
        mimetype="application/pdf"
    )




def generate_qr_for_part(part, force=False):
    """
    part: SparePart instance OR an id/string that uniquely identifies the part
    force: regenerate even if file exists
    Returns relative path to saved QR (e.g. 'qr_codes/part_12.png')
    """
    # allow passing model instance or id
    part_id = getattr(part, "id", part)
    try:
        part_name = getattr(part, "name", f"part_{part_id}")
    except Exception:
        part_name = f"part_{part_id}"

    # Directory inside static
    qr_folder = os.path.join(current_app.root_path, "static", "qr_codes")
    os.makedirs(qr_folder, exist_ok=True)

    # Compose filename (include timestamp if forcing regen to avoid caching)
    if force:
        ts = datetime.utcnow().strftime("%Y%m%d%H%M%S")
        filename = f"part_{part_id}_{ts}.png"
    else:
        filename = f"part_{part_id}.png"

    path = os.path.join(qr_folder, filename)

    # If not forcing and file exists, return relative path
    if os.path.exists(path) and not force:
        return os.path.join("qr_codes", filename)

    # Data encoded in QR — choose whatever you want (ID, SKU, URL)
    # I recommend encoding a simple token like "PART:<id>" or a direct URL to part page.
    # Example token:
    token = f"PART:{part_id}"

    # If you want a URL reachable from the app, use:
    # token = url_for('stock.part_detail', part_id=part_id, _external=True)

    qr = qrcode.QRCode(
        version=2,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=8,
        border=2,
    )
    qr.add_data(token)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")

    img.save(path)
    return os.path.join("qr_codes", filename)
