"""add filed qr_image

Revision ID: 6735ac5060c6
Revises: 
Create Date: 2025-11-02 11:09:09.767298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6735ac5060c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_filename', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_column('qr_filename')

    # ### end Alembic commands ###
