from flask import render_template, redirect, url_for, flash, request , Blueprint , send_file
from app import db
from app.models import Issue , Machine , User
from .forms import IssueForm
from flask_login import current_user
from sqlalchemy import or_
from flask import send_file
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import inch


issues = Blueprint('issues', __name__, template_folder='templates/auth')

# @issues.route("/issues")
# def issues_list():
#     all_issues = Issue.query.all()
#     return render_template("issues/issues.html", issues=all_issues)



@issues.route('/export/pdf')
def export_issues_pdf():
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)

    elements = []
    styles = getSampleStyleSheet()

    # 🏷️ Title
    title_style = ParagraphStyle(
        name="TitleStyle",
        fontSize=18,
        alignment=1,  # center
        spaceAfter=20,
        textColor=colors.HexColor("#2C3E50"),
    )
    elements.append(Paragraph("🧾 Maintenance Issues Report", title_style))
    elements.append(Spacer(1, 12))

    # 📋 Table Header
    data = [["#", "Title", "Machine", "User", "Date", "Status"]]

    # 🧱 Table Rows
    issues = Issue.query.all()
    for i, issue in enumerate(issues, start=1):
        data.append([
            i,
            issue.title,
            issue.machine.name,
            issue.author.username if issue.author else "—",
            issue.created_at.strftime("%Y-%m-%d"),
            issue.status.capitalize() if hasattr(issue, "status") else "—"
        ])

    # 🎨 Table style
    table = Table(data, colWidths=[30, 120, 100, 100, 80, 70])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#34495E")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),

        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#ECF0F1")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),

        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F9F9")]),
    ]))

    elements.append(table)

    # ✍️ Footer
    footer_style = ParagraphStyle(
        name="FooterStyle",
        fontSize=10,
        textColor=colors.HexColor("#7F8C8D"),
        alignment=2,  # right
        spaceBefore=20
    )
    elements.append(Paragraph("Generated by Maintenance System", footer_style))

    # 🧾 Build the document
    doc.build(elements)
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="maintenance_issues_report.pdf",
        mimetype="application/pdf"
    )



@issues.route("/issues")
def issues_list():
    search_query = request.args.get('q', '').strip()
    date_filter = request.args.get('date', '').strip()

    query = Issue.query.join(Issue.machine).join(User) # join Machine table

    if search_query:
        query = query.filter(
            or_(
                Issue.title.ilike(f"%{search_query}%"),
                Machine.name.ilike(f"%{search_query}%"),
                User.username.ilike(f"%{search_query}%")
            )
        )

    if date_filter:
        query = query.filter(Issue.created_at.like(f"%{date_filter}%"))

    issues = query.all()
    return render_template("issues/issues.html", issues=issues)

@issues.route("/issues/new", methods=["GET", "POST"])
def new_issue():
   
    form = IssueForm()
    form.machine_name.choices = [(m.id, m.name) for m in Machine.query.all()]
   
    if form.validate_on_submit():
        issue = Issue(
            title=form.title.data,
            description=form.description.data,
            solution=form.solution.data,
            machine_id = form.machine_name.data,
            author = current_user
        )
        db.session.add(issue)
        db.session.commit()
        flash("Issue added successfully!", "success")
        return redirect(url_for("issues.issues_list"))
    return render_template("issues/add_issue.html", form=form, title="New Issue")

@issues.route("/issues/<int:issue_id>")
def issue_detail(issue_id):
    issue = Issue.query.get_or_404(issue_id)  # returns 404 if not found
    return render_template("issues/issue_details.html", issue=issue)



@issues.route("/issues/<int:issue_id>/edit", methods=["GET", "POST"])
def edit_issue(issue_id):
    issue = Issue.query.get_or_404(issue_id)
    form = IssueForm(obj=issue)
    form.machine_name.choices = [(m.id, m.name) for m in Machine.query.all()]
    if form.validate_on_submit():
        issue.title = form.title.data
        issue.description = form.description.data
        issue.solution = form.solution.data
        issue.machine_name = form.machine_name.data
        db.session.commit()
        flash("Issue updated successfully!", "success")
        return redirect(url_for("issues.issues_list"))
    print(form.errors)
    return render_template("issues/add_issue.html", form=form, title="Edit Issue")

@issues.route("/issues/<int:issue_id>/delete", methods=["POST"])
def delete_issue(issue_id):
    issue = Issue.query.get_or_404(issue_id)
    db.session.delete(issue)
    db.session.commit()
    flash("Issue deleted successfully!", "danger")
    return redirect(url_for("issues.issues_list"))
