<DashboardScreen>:
    name: "dashboard"
    BoxLayout:
        orientation: "vertical"
        padding: 30
        spacing: 20
        canvas.before:
            Color:
                rgba: 0.95, 0.95, 0.95, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Maintenance System"
            font_size: 32
            bold: True
            color: 0.2, 0.2, 0.2, 1
            size_hint_y: 0.2

        Button:
            text: "Perform Transaction (Scan)"
            font_size: 24
            background_color: 0.1, 0.5, 0.8, 1
            color: 1,1,1,1
            size_hint_y: 0.3
            on_press: root.go_to_transaction_choice()

        Button:
            text: "Logout"
            font_size: 22
            background_color: 0.8, 0.2, 0.2, 1
            color: 1,1,1,1
            size_hint_y: 0.2
            on_press: root.logout()
